In [47]:
from __future__ import print_function

import numpy as np
import pandas as pd
import sys

import nsfg
import thinkstats2

In [48]:
preg = nsfg.ReadFemPreg()
preg_map = nsfg.MakePregMap(preg)

#fn for counting no. of pregnancies for a given id
preg_count = lambda id: len(preg_map[id])


count={}
num=0
for key, value in preg_map.items():
    count[key] = len(value)
    if num<10:
        print(key,':',value)
        print(key,':',count[key])
        num += 1
    
        

preg['pregnum'] = preg['caseid'].map(preg_count)
preg['pregnum'][:10]

1 : [0, 1]
1 : 2
2 : [2, 3, 4]
2 : 3
6 : [5, 6, 7]
6 : 3
7 : [8, 9]
7 : 2
12 : [10]
12 : 1
14 : [11, 12, 13]
14 : 3
15 : [14, 15, 16]
15 : 3
18 : [17, 18]
18 : 2
21 : [19, 20]
21 : 2
23 : [21, 22]
23 : 2

0    2
1    2
2    3
3    3
4    3
5    3
6    3
7    3
8    2
9    2
Name: pregnum, dtype: int64

In [49]:
preg.pregnum

0        2
1        2
2        3
3        3
4        3
5        3
6        3
7        3
8        2
9        2
10       1
11       3
12       3
13       3
14       3
15       3
16       3
17       2
18       2
19       2
20       2
21       2
22       2
23       3
24       3
25       3
26       1
27       3
28       3
29       3
        ..
13563    3
13564    3
13565    1
13566    1
13567    2
13568    2
13569    4
13570    4
13571    4
13572    4
13573    2
13574    2
13575    1
13576    2
13577    2
13578    2
13579    2
13580    3
13581    3
13582    3
13583    2
13584    2
13585    3
13586    3
13587    3
13588    5
13589    5
13590    5
13591    5
13592    5
Name: pregnum, Length: 13593, dtype: int64

In [50]:
preg.caseid.value_counts()

9786     19
7142     14
5272     14
2195     12
1597     12
4246     11
6297     11
1169     11
601      10
12413    10
5268     10
2265     10
413      10
9517     10
6446     10
2678     10
3523     10
5699      9
12018     9
1791      9
9466      9
10185     9
3808      9
8702      9
2408      9
1747      9
12477     9
1214      9
2126      9
989       9
         ..
985       1
52        1
2093      1
4325      1
11472     1
4121      1
11187     1
950       1
2770      1
1090      1
2071      1
3000      1
7058      1
6173      1
4793      1
1122      1
3163      1
7342      1
7050      1
5020      1
7069      1
7090      1
9109      1
4801      1
5028      1
12312     1
11172     1
11180     1
2983      1
7146      1
Name: caseid, Length: 5033, dtype: int64

In [51]:
preg.pregnum[preg.caseid==9786]

10602    19
10603    19
10604    19
10605    19
10606    19
10607    19
10608    19
10609    19
10610    19
10611    19
10612    19
10613    19
10614    19
10615    19
10616    19
10617    19
10618    19
10619    19
10620    19
Name: pregnum, dtype: int64

In [52]:
preg.pregnum[preg.caseid==9786].values

array([19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 19])

In [53]:
preg[preg.caseid==9786]

,caseid,pregordr,howpreg_n,howpreg_p,moscurrp,nowprgdk,pregend1,pregend2,nbrnaliv,multbrth,...,laborfor_i,religion_i,metro_i,basewgt,adj_mod_basewgt,finalwgt,secu_p,sest,cmintvw,totalwgt_lb
10602,9786,1,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10603,9786,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,9.9375
10604,9786,3,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10605,9786,4,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10606,9786,5,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,8.1875
10607,9786,6,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10608,9786,7,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10609,9786,8,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10610,9786,9,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10611,9786,10,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,8.5625
10612,9786,11,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10613,9786,12,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10614,9786,13,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10615,9786,14,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10616,9786,15,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10617,9786,16,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10618,9786,17,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,8.1875
10619,9786,18,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN
10620,9786,19,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,0,0,0,3409.533458,3924.429085,7161.690638,2,70,NaN,NaN

In [54]:
preg.pregnum[preg.caseid==989]

1106    9
1107    9
1108    9
1109    9
1110    9
1111    9
1112    9
1113    9
1114    9
Name: pregnum, dtype: int64